name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov ruff cfn-lint aws-sam-cli

    - name: Run tests
      run: pytest -q --maxfail=1 --cov=backend --cov-report=term-missing

    - name: Run linter (Ruff)
      run: ruff check .

    - name: Validate SAM template
      run: cfn-lint infra/sam-template.yaml

    - name: Build SAM application
      run: sam build --template infra/sam-template.yaml

    - name: Validate SAM application
      run: sam validate --template infra/sam-template.yaml
